const products = {
    anta: [
        {
            id: 'anta-1',
            name: 'Giày WIND TUNNEL 4.0 A-FLASHEDGE ANTA 1124A1605-2',
            price: 1160000,
            image: './images/product/anta/product1.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p><strong>Giày bóng rổ nam WIND TUNNEL 4.0 A-FLASHEDGE ANTA 1124A1605-2</strong></p><p>Giày bóng rổ ANTA WIND TUNNEL 4.0 - sự lựa chọn tuyệt vời để chơi bóng rổ đường phố. Đôi giày này phù hợp cho việc tập luyện và chơi bóng hằng ngày. Đế giữa A-FLASHEDGE mang lại mức độ đệm cao, giảm thiểu mệt mỏi và mang lại sự thoải mái trong nhiều giờ liên tục.</p><p><strong>THÔNG TIN CHI TIẾT:</strong></p><p><strong>Thương hiệu: </strong>ANTA</p><p><strong>Màu sắc: </strong>Giày ANTA Wind Tunnel 4.0 A-FLASHEDGE 1124A1605-2 là phiên bản màu đen cá tính, giúp đôi giày như một “chiến binh” mỗi khi ra sân.</p><p><strong>Bề mặt:</strong> Phần trên của giày bóng rổ được làm bằng lưới nilon thoáng khí, da tổng hợp bền bỉ và TPU giúp bảo vệ tốt bàn chân, hạn chế chấn thương, giữ đôi chân luôn thông thoáng</p><p><strong>Lưỡi gà: </strong>Phần lưỡi gà cao, phần đầu được bọc da, giúp duy trì form, nửa dưới làm bằng lưới thoáng khí, ôm sát mu bàn chân, giúp đôi chân luôn khô giáo, thoải mái khi chơi bóng</p><p><strong>Đế giữa:</strong>Đế giữa của giày bóng rổ Wind Tunnel 4.0 áp dụng công nghệ đàn hồi A-FLASHEDGE Anta mới nhất, với độ bền tốt và khả năng đàn hồi đệm, mang lại hiệu ứng bật tốt hơn, đồng thời duy trì cảm giác mềm mại và thoải mái cho bàn chân. Loại đế này có khả năng biến dạng thích ứng, làm tăng diện tích tiếp xúc của đế với bề mặt. Khi môi trường bên ngoài thay đổi, các phân tử của vật liệu này sẽ thích ứng, cho phép nó duy trì đặc tính hấp thụ sốc.</p><p><strong>Đế ngoài: </strong>Đế ngoài làm bằng xốp EVA/TPU/Cao su, chống mòn tốt, thiết kế các vân rãnh giúp hạn chế trơn trượt hiệu quả, độ co ngót ổn định và độ linh hoạt tốt</p><p><strong>Ứng dụng: </strong>Wind Tunnel 4.0 A-FLASHEDGE là dòng giày bóng rổ chuyên dụng, được thiết kế cho người chơi bóng ở mọi vị trí và môi trường tập luyện hay thi đấu, đặc biệt là với sân bóng ngoài trời</p>'
        },
        {
            id: 'anta-2',
            name: 'Giày WIND TUNNEL 4.0 A-FLASHEDGE ANTA 1124A1605-3',
            price: 1160000,
            image: './images/product/anta/product2.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p><strong>Giày bóng rổ nam WIND TUNNEL 4.0 A-FLASHEDGE ANTA 1124A1605-3</strong></p><p>Giày Anta WIND TUNNEL 4.0 A-FLASHEDGE được thiết kế dành riêng cho những người đam mê bóng rổ, đôi giày này mang đến sự kết hợp hoàn hảo giữa hiệu suất và thời trang. Đế giày bóng rổ sử dụng công nghệ A-Lashedge tối ưu hóa độ bám và độ ổn định, giúp bạn tự tin di chuyển linh hoạt trên sân.</p><p><strong>THÔNG TIN CHI TIẾT:</strong></p><p><strong>Thương hiệu: </strong>ANTA</p><p><strong>Màu sắc: </strong>Giày ANTA Wind Tunnel 4.0 A-FLASHEDGE 1124A1605-3 là phiên bản màu đặc biệt với sự pha trộn giữa xám và trắng, mang tới đôi giày với màu sắc thời thượng nhưng cũng rất cá tính.</p><p><strong>Bề mặt: </strong>Phần trên của giày bóng rổ được làm bằng lưới thoáng khí, thiết kế thông gió tiên tiến giúp duy trì sự thoáng khí và thoải mái, giảm thiểu nhiệt độ và độ ẩm bên trong giày. Da tổng hợp bền bỉ và TPU giúp bảo vệ tốt bàn chân, hạn chế chấn thương, giữ đôi chân luôn thông thoáng</p><p><strong>Lưỡi gà: </strong>Phần lưỡi gà cao, phần đầu được bọc da, giúp duy trì form, nửa dưới làm bằng lưới thoáng khí, ôm sát mu bàn chân, giúp đôi chân luôn khô giáo, thoải mái khi chơi bóng</p><p><strong>Đế giữa: </strong>Đế giữa của giày bóng rổ Wind Tunnel 4.0 áp dụng công nghệ đàn hồi A-FLASHEDGE Anta mới nhất, với độ bền tốt và khả năng đàn hồi đệm, mang lại hiệu ứng bật tốt hơn, đồng thời duy trì cảm giác mềm mại và thoải mái cho bàn chân. Loại đế này có khả năng biến dạng thích ứng, làm tăng diện tích tiếp xúc của đế với bề mặt. Khi môi trường bên ngoài thay đổi, các phân tử của vật liệu này sẽ thích ứng, cho phép nó duy trì đặc tính hấp thụ sốc.</p><p><strong>Đế ngoài: </strong>Đế ngoài làm bằng xốp EVA/TPU/Cao su, chống mòn tốt, thiết kế các vân rãnh giúp hạn chế trơn trượt hiệu quả, độ co ngót ổn định và độ linh hoạt tốt</p><p><strong>Ứng dụng: </strong>Giày Anta Wind Tunnel 4.0 A-FLASHEDGE là dòng giày bóng rổ chuyên dụng, được thiết kế hỗ trợ cho người chơi bóng ở mọi vị trí trên sân. Với vẻ ngoài thời trang, bạn cũng có thể sử dụng như một đôi giày thời trang thể thao cá tính.</p>'
        },
        {
            id: 'anta-3',
            name: 'Giày SHOCK WAVE 5.0 V2 NITROEDGE ANTA 1124A1106-2',
            price: 2390000,
            image: './images/product/anta/product3.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p><strong>Giày bóng rổ nam SHOCK WAVE 5.0 V2 NITROEDGE ANTA 1124A1106-2</strong></p><p>Giày Anta SHOCK WAVE 5.0 V2 đôi giày bóng rổ lý tưởng cho sân đấu ngoài trời, với ngoại hình cool ngầu, sở hữu chất lượng cực tốt, cực bền với chất liệu cao cấp. TPU chống lật kéo dài gần full đế, giúp bảo vệ hiệu quả đôi chân bạn khỏi những chấn thương. SHOCK WAVE - cùng các chiến binh ra sân với 200% sức mạnh.</p><p><strong>THÔNG TIN CHI TIẾT:</strong></p><p><strong>Thương hiệu: </strong>ANTA</p><p><strong>Màu sắc: </strong>Pha trộn giữa màu be và đen mang lại vẻ ngoài cá tính, với SHOCK WAVE 5.0 bạn không chỉ là chiến binh trên sân đấu mà còn là minh tinh trước đám đông</p><p><strong>Bề mặt: </strong>SHOCK WAVE 5.0 được làm từ chất liệu vải lưới/TPU/sợi carbon, duy trì form dáng tốt, bền bỉ và bảo vệ tốt bàn chân khỏi chấn thương và mang lại sự thông thoáng tuyệt vời.</p><p><strong>Mũi giày: </strong>Bọc viền cao, giúp mũi giày luôn cứng cáp, dễ dàng vệ sinh, bảo vệ ngón chân</p><p><strong>Lưỡi gà: </strong>Phần lưỡi gà cao, thiết kế đặc biệt với nửa trên được bọc da giúp đôi giày ấn tượng, giữ form ổn định, nửa dưới là chất liệu lưới đan rộng, thoáng khí, giúp đôi chân luôn thoải mái khi chơi bóng</p><p><strong>Gót giày: </strong>Được bọc da toàn bộ, giúp ôm gọn và bảo vệ gót chân, hạn chế chấn thương. Công nghệ SmartSam được sử dụng ở vùng gót chân, cho phép giày bóng rổ SHOCK WAVE 5.0 mới nhẹ bẫng như bọt. Phản hồi đôi chân nhạy hơn sau các cú bật nhảy nhờ vô số khoảng trống li ti nhiệm màu.</p><p><strong>Đế giữa: </strong>Giày SHOCK WAVE 5.0 được ứng dụng công nghệ đế giữa NitroEdge, tỉ lệ quy hồi năng lượng lên tới 82,6%, giúp bạn tiết kiệm năng lượng và tăng cường sức mạnh cho mỗi đòn tấn công, màng lại sự ổn định và an toàn cho từng bước di chuyển.</p><p><strong>Đế ngoài: </strong>Bộ đế siêu bền thách thức mọi mặt sân, lớp đế cao su chống mòn với những đường vân bám sân hoàn hảo và lâu dài, giúp bạn tự tin trên mọi mặt sân, dù là sân khó tính nhất. TPU chống lật kéo dài gần full đế, nay tăng cường đai bảo vệ, hạn chế tối đa trật trẹo khớp chân</p><p><strong>Ứng dụng: </strong>SHOCK WAVE 5.0 được thiết kế cho người chơi bóng rổ thuận lợi từ di chuyển, tấn công, thích hợp cho cả tập luyện và thi đấu chuyên nghiệp</p>'
        },
        {
            id: 'anta-4',
            name: 'Giày SHOCK WAVE 5.0 V2 NITROEDGE ANTA 1124A1106-3',
            price: 2390000,
            image: './images/product/anta/product4.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p><strong>Giày bóng rổ nam SHOCK WAVE 5.0 V2 NITROEDGE ANTA 1124A1106-3</strong></p><p>ANTA SHOCK WAVE 5.0 V2 là đôi giày bóng rổ Anta được thiết kế với sự cộng tác của cầu thủ NBA và Dallas Mavericks Kyrie Irving. Đôi giày cho phép bạn tiếp đất và bật nhảy nhanh chóng, giúp bạn luôn đi trước một bước. Đặc biệt, đế giữa sử dụng công nghệ NITROEDGE hiện đại nhất, cung cấp mức độ đệm cao trong khi vẫn nhẹ và linh hoạt.</p><p><strong>THÔNG TIN CHI TIẾT:</strong></p><p><strong>Thương hiệu:</strong> ANTA</p><p><strong>Màu sắc:</strong> Giày Anta SHOCK WAVE 5.0 V2 1124A1106-3 là phiên bản phối màu giữa trắng và xanh da trời, trẻ trung, bắt mắt</p><p><strong>Bề mặt: </strong>Upper được làm từ chất liệu vải lưới/TPU/sợi carbon, duy trì form dáng tốt, bền bỉ và bảo vệ tốt bàn chân khỏi chấn thương và mang lại sự thông thoáng tuyệt vời.</p><p><strong>Mũi giày: </strong>Bọc viền cao, giúp mũi giày luôn cứng cáp, bảo vệ ngón chân</p><p><strong>Lưỡi gà: </strong>Phần lưỡi gà cao, thiết kế đặc biệt với nửa trên được bọc da giúp đôi giày bóng rổ ấn tượng, giữ form ổn định, nửa dưới là chất liệu vải lưới, lỗ thoáng khí phân bổ theo từng vị trí, giúp đôi chân luôn thoải mái khi chơi bóng</p><p><strong>Gót giày: </strong>Được bọc da toàn bộ, giúp ôm gọn và bảo vệ gót chân, hạn chế chấn thương. Công nghệ SmartSam được sử dụng ở vùng gót chân, cho phép giày bóng rổ SHOCK WAVE 5.0 mới nhẹ bẫng như bọt. Phản hồi đôi chân nhạy hơn sau các cú bật nhảy nhờ vô số khoảng trống li ti nhiệm màu.</p><p><strong>Đế giữa: </strong>Miếng đệm để hỗ trợ một bên của bàn chân bao gồm ba tấm có độ cứng khác nhau. Miếng đầu tiên với công nghệ SUPERFLEXI nằm ở khu vực ngón chân, miếng thứ hai ở giữa và miếng thứ ba ở gót chân. Thiết kế này đảm bảo độ ổn định cao hơn và cho phép bạn trải nghiệm cuộc chơi theo một cách mới. Đế giữa giày Anta SHOCK WAVE 5.0 được ứng dụng công nghệ NitroEdge, tỉ lệ quy hồi năng lượng lên tới 82,6%, giúp bạn tiết kiệm năng lượng và tăng cường sức mạnh cho mỗi đòn tấn công, mang lại sự ổn định và an toàn cho từng bước di chuyển.</p><p><strong>Đế ngoài: </strong>Bộ đế giày bóng rổ siêu bền thách thức mọi mặt sân, đế ngoài Cement Killer chống mài mòn, mức độ bám đường cao mang lại cảm giác sân tuyệt vời. TPU chống lật kéo dài gần full đế, tăng cường đai bảo vệ, hạn chế tối đa trật khớp chân.</p><p><strong>Ứng dụng: </strong>SHOCK WAVE 5.0 được thiết kế cho người chơi bóng rổ thuận lợi từ di chuyển, tấn công, thích hợp cho cả tập luyện và thi đấu chuyên nghiệp</p>'
        },
        {
            id: 'anta-5',
            name: 'Giày SHOCK WAVE 5.0 V2 NITROEDGE ANTA 1124A1106-9',
            price: 2390000,
            image: './images/product/anta/product5.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p><strong>Giày bóng rổ nam SHOCK WAVE 5.0 V2 NITROEDGE ANTA 1124A1106-9</strong></p><p>Giày Anta SHOCK WAVE 5.0 V2 được thiết kế lấy cảm hứng từ những loài động vật hoang dã và hung dữ, sẵn sàng làm bất cứ điều gì để giành chiến thắng. Đôi giày lý tưởng cho sân chơi ngoài trời, với cấu trúc đế siêu bền. Đế giữa giày bóng rổ được ứng dụng công nghệ NitroEdge, tỉ lệ quy hồi năng lượng lên tới 82,6%, giúp bạn tiết kiệm năng lượng và tăng cường sức mạnh cho mỗi đòn tấn công.</p><p><strong>THÔNG TIN CHI TIẾT:</strong></p><p><strong>Thương hiệu: </strong>ANTA</p><p><strong>Màu sắc: </strong>SHOCK WAVE 5.0 V2 1124A1106-9 là phiên bản giày bóng rổ với màu đen cá tính, phần logo màu vàng nổi bật, làm điểm nhấn cho đôi giày</p><p><strong>Bề mặt: </strong>Upper được làm từ chất liệu vải lưới/TPU/sợi carbon, duy trì form dáng tốt, bền bỉ và bảo vệ tốt bàn chân khỏi chấn thương và mang lại sự thông thoáng tuyệt vời.</p><p><strong>Lưỡi gà: </strong>Phần lưỡi gà cao, thiết kế đặc biệt với nửa trên được bọc da giúp đôi giày bóng rổ ấn tượng, giữ form ổn định, nửa dưới là chất liệu vải lưới, lỗ thoáng khí phân bổ theo từng vị trí, giúp đôi chân luôn thoải mái khi chơi bóng</p><p><strong>Gót giày: </strong>Được bọc da toàn bộ, giúp ôm gọn và bảo vệ gót chân, hạn chế chấn thương. Công nghệ SmartSam được sử dụng ở vùng gót chân, cho phép giày bóng rổ SHOCK WAVE 5.0 mới nhẹ bẫng như bọt. Phản hồi đôi chân nhạy hơn sau các cú bật nhảy nhờ vô số khoảng trống li ti nhiệm màu.</p><p><strong>Đế giữa: </strong>Miếng đệm để hỗ trợ một bên của bàn chân bao gồm ba tấm có độ cứng khác nhau. Miếng đầu tiên với công nghệ SUPERFLEXI nằm ở khu vực ngón chân, miếng thứ hai ở giữa và miếng thứ ba ở gót chân. Thiết kế này đảm bảo độ ổn định cao hơn và cho phép bạn trải nghiệm cuộc chơi theo một cách mới. Đế giữa giày Anta SHOCK WAVE 5.0 được ứng dụng công nghệ NitroEdge, cung cấp mức độ đệm cao trong khi vẫn nhẹ và linh hoạt. Một tấm carbon và miếng đệm đôi ở giữa bàn chân bằng TPU được thiết kế để bảo vệ chống xoắn.</p><p><strong>Đế ngoài: </strong>Bộ đế giày bóng rổ siêu bền thách thức mọi mặt sân, đế ngoài Cement Killer chống mài mòn, mức độ bám đường cao mang lại cảm giác sân tuyệt vời. TPU chống lật kéo dài gần full đế, tăng cường đai bảo vệ, hạn chế tối đa trật khớp chân.</p><p><strong>Ứng dụng: </strong>Giày Anta SHOCK WAVE 5.0 được thiết kế cho người chơi bóng rổ thuận lợi từ di chuyển, tấn công, thích hợp cho cả tập luyện và thi đấu chuyên nghiệp</p>'
        },
    ],
    lining: [
        {
            id: 'lining-1',
            name: 'Giày Li-Ning Wade 808 2 Dynasty ABPS037-2',
            price: 1490000,
            image: './images/product/lining/product1.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p>Giày Li-Ning bóng rổ nam ABPS037-2 là một đôi giày chuyên dụng được thiết kế đặc biệt để mang lại hiệu suất tốt cho các vận động viên nam chơi bóng rổ. Đây là một mẫu giày từ thương hiệu Li-Ning, một thương hiệu thể thao nổi tiếng và được tin dùng.</p><p>ABPS037-2 có một thiết kế thể thao và hiện đại, với sự kết hợp giữa tính năng và thẩm mỹ. Phần trên của giày được làm từ chất liệu tổng hợp chất lượng cao, mang lại độ bền và khả năng chống mài mòn. Với lớp vải lưới tạo sự thoáng khí và tăng cường sự thông thoáng cho đôi chân trong quá trình sử dụng.</p><p>Phần đế giày của ABPS037-2 được làm từ cao su chất lượng, có độ ma sát tốt và độ bám cao. Điều này giúp cung cấp độ ổn định và độ linh hoạt cho người mang giày trong quá trình chuyển động nhanh và nhảy cao.</p><p>Giày cũng được trang bị công nghệ đệm tiên tiến, giúp giảm lực va đập lên chân và mang lại sự thoải mái trong quá trình sử dụng. Hệ thống hỗ trợ cổ chân và ngón chân được tích hợp để tăng cường sự ổn định và giảm nguy cơ chấn thương.</p><p>ABPS037-2 cung cấp sự hỗ trợ và linh hoạt cần thiết cho các vận động viên bóng rổ nam. Đây là một lựa chọn tuyệt vời cho những người đang tìm kiếm một đôi giày chất lượng cao, có khả năng chống mài mòn và mang lại sự thoải mái và ổn định trong quá trình chơi bóng rổ.</p><p><strong>Thương hiệu:</strong> Li-Ning</p><p><strong>Thiết kế: </strong>Li-Ning</p><p><strong>Mã sản phẩm: </strong>ABPS037-2</p><p><strong>Xuất xứ:</strong> Trung Quốc</p>'
        },
        {
            id: 'lining-2',
            name: 'Li-Ning Sonic 10 V2 Low Purple Red ABAS057-6',
            price: 1690000,
            image: './images/product/lining/product2.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p>Giày Li-Ning bóng rổ nam ABAS057-6 là một đôi giày chuyên dụng được thiết kế để mang lại hiệu suất tốt cho các vận động viên bóng rổ nam. Đây là mẫu giày của thương hiệu Li-Ning, một thương hiệu nổi tiếng trong ngành giày thể thao.</p><p>Giày ABAS057-6 có thiết kế đẹp mắt và phong cách, với sự kết hợp giữa tính năng và thẩm mỹ. Chúng có một lớp vỏ ngoài bằng chất liệu tổng hợp chất lượng cao, giúp tăng độ bền và chống mài mòn. Lớp vải lưới được sử dụng ở phần trên giày để tăng cường sự thoáng khí và giảm cảm giác nóng bức khi sử dụng.</p><p>Phần đế giày của ABAS057-6 được làm từ cao su chất lượng, có độ ma sát tốt và độ bám cao. Điều này giúp cung cấp độ ổn định và độ linh hoạt cho người mang giày trong quá trình chuyển động nhanh và nhảy cao.</p><p>Giày cũng được trang bị hệ thống đệm tốt nhờ công nghệ tiên tiến, giúp giảm lực va đập lên chân và mang lại sự êm ái trong suốt quá trình sử dụng. Ngoài ra, chúng còn có hệ thống hỗ trợ cổ chân và ngón chân giúp tăng cường sự ổn định và giảm nguy cơ chấn thương.</p><p>Giày Li-Ning ABAS057-6 là một sự lựa chọn tốt cho những người chơi bóng rổ nam, những người đang tìm kiếm một đôi giày có độ bền cao, tính linh hoạt và hỗ trợ tốt cho chuyển động trong sân.</p><p><strong>Thương hiệu:</strong> Li-Ning</p><p><strong>Thiết kế: </strong>Li-Ning</p><p><strong>Mã sản phẩm:</strong>ABAS057-6</span></p><p><strong>Xuất xứ:</strong> Trung Quốc</p>'
        },
        {
            id: 'lining-3',
            name: 'Giày Li-Ning Speed 9 Sweet Orange ABAT023-4',
            price: 2990000,
            image: './images/product/lining/product3.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p>Giày Li-Ning bóng rổ nam ABAT023-4 là một đôi giày chuyên dụng được thiết kế đặc biệt cho các vận động viên nam chơi bóng rổ. Đôi giày này thuộc dòng sản phẩm cao cấp của thương hiệu Li-Ning, nổi tiếng với chất lượng và hiệu suất của sản phẩm thể thao.</p><p>Giày Li-Ning ABAT023-4 có thiết kế đẹp mắt và thời trang, kết hợp sự cân đối giữa chất liệu và màu sắc. Chúng được làm từ chất liệu tổng hợp chất lượng cao, kết hợp với lớp lưới thoáng khí, giúp cung cấp sự thoải mái và đảm bảo sự thông thoáng cho chân trong quá trình chơi bóng rổ.</p><p>Một trong những điểm nổi bật của giày Li-Ning ABAT023-4 là hệ thống đệm tiên tiến. Giày được trang bị công nghệ đệm chất lượng cao, giúp giảm sốc và tăng cường sự thoải mái khi nhảy lên và đạp xuống sàn. Điều này giúp bảo vệ xương và khớp chân, và giúp người chơi có thể di chuyển linh hoạt và thực hiện các động tác nhảy cao, chuyền bóng và cắt giữa trận đấu.</p><p>Đế giày của ABAT023-4 được thiết kế đặc biệt để cung cấp độ bám đất tốt và ổn định. Họa tiết và cấu trúc đế giày được tối ưu hóa để cung cấp sự bám dính và độ linh hoạt khi chuyển động nhanh trên sân bóng rổ. Điều này cho phép người chơi có sự kiểm soát tốt hơn khi di chuyển và thực hiện các động tác quan trọng trong trận đấu.</p><p>Tóm lại, giày Li-Ning bóng rổ nam ABAT023-4 là một lựa chọn tuyệt vời cho các vận động viên nam chơi bóng rổ. Chúng cung cấp sự thoải mái, độ bền và hiệu suất cao, giúp người chơi tự tin và tận hưởng trọn vẹn trận đấu.</p><p><strong>Thương hiệu:</strong> Li-Ning</p><p><strong>Thiết kế: </strong>Li-Ning</p><p><strong>Mã sản phẩm: </strong>ABAT023-4</p><p><strong>Xuất xứ:</strong> Trung Quốc</p>'
        },
        {
            id: 'lining-4',
            name: 'Giày Li-Ning Wade Son of Flash White Hot ABPT019-6',
            price: 3490000,
            image: './images/product/lining/product4.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p>Giày Li-Ning bóng rổ nam ABPT019-6 là một đôi giày chuyên dụng được thiết kế đặc biệt cho các vận động viên nam chơi bóng rổ. Đôi giày này thuộc vào dòng sản phẩm cao cấp của thương hiệu Li-Ning, nổi tiếng với chất lượng và hiệu suất của sản phẩm thể thao.</p><p>ABPT019-6 có một thiết kế đẹp mắt và mạnh mẽ, mang đến sự tự tin và phong cách cho người mang. Chúng được làm từ chất liệu tổng hợp chất lượng cao, kết hợp với lớp lưới thoáng khí, giúp tăng cường sự thoải mái và đảm bảo sự thông thoáng cho chân trong quá trình chơi bóng rổ.</p><p>Một trong những điểm nổi bật của giày Li-Ning ABPT019-6 là hệ thống đệm tiên tiến. Giày được trang bị công nghệ đệm chất lượng cao, giúp giảm sốc và tăng cường sự thoải mái khi nhảy lên và đạp xuống sàn bóng. Điều này giúp bảo vệ xương và khớp chân, và giúp người chơi có thể di chuyển linh hoạt và thực hiện các động tác nhảy cao, chuyền bóng và cắt giữa trận đấu.</p><p>Đế giày của ABPT019-6 được thiết kế để cung cấp độ bám đất tốt và ổn định. Họa tiết và cấu trúc đế giày được tối ưu hóa để cung cấp sự bám dính và độ linh hoạt khi chuyển động nhanh trên sân bóng rổ. Điều này giúp người chơi có sự kiểm soát tốt hơn khi di chuyển và thực hiện các động tác quan trọng trong trận đấu.</p><p><strong>Thương hiệu:</strong> Li-Ning</p><p><strong>Thiết kế: </strong>Li-Ning</p><p><strong>Mã sản phẩm:</strong> ABPT019-6</p><p><strong>Xuất xứ:</strong> Trung Quốc</p>'
        },
        {
            id: 'lining-5',
            name: 'Giày Li-Ning Way of Wade 10 Sunshine State ABAS115-9',
            price: 5390000,
            image: './images/product/lining/product5.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p><strong>Giày Li-Ning Way of Wade 10 Sunshine State ABAS115-9: Biểu tượng của sự rực rỡ</strong></p><p>Thiết kế lấy cảm hứng từ Florida:</p><ul><li>Lấy cảm hứng từ bang Florida rực rỡ, Sunshine State mang sắc cam tươi sáng làm chủ đạo, kết hợp với các điểm nhấn màu vàng và xanh dương, tạo nên diện mạo năng động và thu hút.</li><li>Logo Wade được thêu nổi bật trên lưỡi gà, khẳng định sự đẳng cấp của dòng sản phẩm Way of Wade.</li><li>Các họa tiết lấy cảm hứng từ tia nắng mặt trời được in chìm trên thân giày, thể hiện tinh thần nhiệt huyết và rực rỡ của Florida.</li></ul><p>Công nghệ tiên tiến:</p><ul><li>Công nghệ đệm BOOM mang lại khả năng đàn hồi và trợ lực tối ưu, hỗ trợ di chuyển linh hoạt và bứt tốc mạnh mẽ.</li><li>Lớp đệm lót Litefoam nhẹ và êm ái, giúp giảm chấn hiệu quả và mang lại cảm giác thoải mái khi di chuyển.</li><li>Chất liệu cao cấp được sử dụng cho phần thân giày, đảm bảo độ bền bỉ và thoáng khí, phù hợp cho các hoạt động thể thao cường độ cao.</li></ul><p>Phiên bản giới hạn:</p><ul><li>Sunshine State là phiên bản giới hạn, được sản xuất với số lượng có hạn, góp phần tăng thêm giá trị và sự độc đáo cho đôi giày.</li></ul><p>Phù hợp cho:</p><ul><li>Giày Li-Ning Way of Wade 10 Sunshine State ABAS115-9 là lựa chọn hoàn hảo cho những người yêu thích bóng rổ, đặc biệt là fan hâm mộ của Dwyane Wade.</li><li>Đôi giày cũng phù hợp cho các hoạt động thể thao khác như tập gym, chạy bộ hay đơn giản là đi chơi dạo phố.</li></ul><p>Kết luận:</p><p>Giày Li-Ning Way of Wade 10 Sunshine State ABAS115-9 là sự kết hợp hoàn hảo giữa thiết kế thời trang, công nghệ tiên tiến và giá trị sưu tầm. Đôi giày hứa hẹn sẽ mang đến trải nghiệm tuyệt vời cho người sử dụng.</p><h3>Thông tin sản phẩm Giày Li-Ning Way of Wade 10 Sunshine State</h3><p><strong>Thương hiệu :</strong> Lining</p><p><strong>Thiết kế:</strong>Way of Wade</p><p><strong>Mã sản phẩm:</strong> ABAS115-9</p><p><strong>Xuất xứ:</strong> Trung Quốc</p>'
        },
    ],
    peak: [
        {
            id: 'peak-1',
            name: 'Giày PEAK Monster Low E241511A – Trắng Hồng',
            price: 1251000,
            image: './images/product/peak/product1.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p>Giày bóng rổ nam E241511A<br>Thương hiệu: PEAK<br><p>Chức năng: hấp thụ sốc, chống trượt, chống mài mòn, thoáng khí, thấm mồ hôi, bao bọc<br>Thiết kế và công nghệ: P – MOTIVE<br>Thích hợp chơi: trong nhà và ngoài trời </p><p>PEAK BASKETBALL E241511A với phối màu cực đỉnh kết hợp cùng những đường khâu tỉ mỉ tạo thành 1 tổng thể hài hòa</p><p>- Upper lưới kỹ thuật kết hợp chất liệu da PU cường độ cao đáp ứng nhu cầu chơi trên sân, vải lưới ren thắt chặt cải thiện<br>khả năng hỗ trợ ở phần giữa giày đồng thời thoáng khí </p><p>- Thiết kế cổ Lowcut linh hoạt và dễ di chuyển thích hợp với vị trí số Hậu vệ 1 trên sân</p><p>- TPU diện tích lớn lộn ngược ở giữa cung cấp sự hỗ trợ tuyệt vời ở giữa giày </p><p>- Đế giữa công nghệ P-Motive giúp tăng khả năng bật nhảy cũng như phản hồi nhanh chóng các chuyển động chân</p><p>- Đế gót bằng da tổng hợp giúp khóa gót chân, hỗ trợ và ổn định toàn bộ phần gót</p><p>- Đế ngoài cao su chống mài mòn ngay cả khi chơi ở sàn xi măng </p><p>CÔNG DỤNG:<br>Giày bóng rổ chuyên đánh Outdoor, với thiết kế và công nghệ đế độc quyền chỉ có trên các dòng cao cấp nhà PEAK giúp bạn cày bền bỉ trên mọi loại sân chống trơn trượt chống mài mòn. Phần thiết kế thân giày và cổ giày bảo vệ chân, phản hồi chuyển động, bức tốc và hỗ trợ bật nhảy tốt. Có thể sử dụng chơi các bộ môn thể thao tương tự: cầu lông, bóng rổ indoor, chạy bộ đi bộ nhẹ nhàng</p>'
        },
        {
            id: 'peak-2',
            name: 'Giày PEAK Lightning X Performance ET32101A – Hồng Khaki',
            price: 1463000,
            image: './images/product/peak/product2.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p>Thương hiệu: PEAK<br>Chức năng: hấp thụ sốc, chống trượt, chống mài mòn, thoáng khí, thấm mồ hôi, bao bọc, hỗ trợ, cân bằng, chống va đập, nhẹ, tăng, bật<br>Chất liệu đế ngoài: cao su chống mài mòn</p><p>Lấy cảm hứng về cảm giác tốc độ của “Tia Chớp” những đường nét uyển chuyển như sấm sét. PEAK Lightning X là phiên bản mới nhất, hoàn thiện và tích hợp nhiều công nghệ hiện đại nhất của series PEAK Lightning với bảng màu sắc đặc biệt.</p><p>Thiết kế và công nghệ:</p><p>– Upper là mesh cao cấp cùng sợi TPU cho kết cấu chặt chẽ, chắc chắn và gia tăng độ bền khi sử dụng.<br>– Cổ giày êm ái giúp ôm sát chân mà vẫn đảm bảo độ thoải mái.<br>– Công nghệ P-SOON lần đầu tiên xuất hiện trong series PEAK Lightning được tích hợp phía trước của đế giữa, giúp gia tăng khả năng đàn hồi năng lượng. Công nghệ Super P-Motive tích hợp trên toàn bộ đế giữa, biến đế giữa thành một tấm phản lực hỗ trợ gia tăng sực bật, bứt tốc cực nhanh. Vật liệu TAICHI tích hợp ở phía sau đế giữa, hỗ trợ khả năng tiếp đất và giảm trọng lượng cho giày.<br>- Tấm TPU chữ X ở đế giày chống xoắn cho giày, đặc biệt thích hợp sử dụng thi đấu cường độ cao.<br>- Đế ngoài cao su RB cao cấp, hạn chế mài mòn và chống trơn trượt.</p>'
        },
        {
            id: 'peak-3',
            name: 'Giày PEAK PEAK Taichi Big Triangle 3 ET41107A – Hồng',
            price: 1791000,
            image: './images/product/peak/product3.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p>Tên sản phẩm: Giày  bóng rổ nam PEAK TAICHI BIG TRIANGLE 3  ET41107A<br>- Ưu điểm:  bám sân outdoor tốt, hấp thụ sốc, chống trượt, chống mài mòn,  hỗ trợ, cân bằng, chống va đập, nhẹ, tăng, bật<br>- Công nghệ: Super P-Motive, Công nghệ PEAK Taichi</p><p>Thuộc series giày bóng rổ cao cấp dòng Big Triangle đã phát triển đến kỷ nguyên thứ 3 lấy cảm hứng từ “YEAR OF DRAGON” với phiên bản kép cải tiến về công nghệ lẫn thiết kế mang đến siêu phẩm giày bóng rổ có độ đàn hồi dồi dào cung cấp sức mạnh không giới hạn cho ballers </p><p>- Chất liệu vải lưới đàn hồi thoáng khí, nhẹ linh hoạt kết cấu chặt chẽ tăng độ dẻo dai cho sản phẩm, nhìn bao quát sẽ tạo nên tổng thể vừa vặn và thoải mái</p><p>- Công nghệ kép Super P-Motive kết hợp công nghệ P- SOON mang đến cho thân giày hiệu suất phục hồi và đàn hồi giống như một tấm phản lực với độ bật nảy lên đến 65% giúp khởi động nhanh và gia tăng khả năng phản hồi năng lượng</p><p>- Công nghệ PEAK Taichi ở đệm đế sau hỗ trợ quá trình đàn hồi tiếp đất khi bật nhảy đồng thời giảm trọng lượng cho giày.<br>Khung TPU bọc quanh gót chân chống xoắn và hỗ trợ cân bằng cho toàn bộ thân giày </p><p>- Kết cấu đế ngoài cao su Bionic thêm đường phân bổ tự nhiên ở lòng bàn chân tăng hiệu suất chống trơn trượt giúp chuyển động của chân mượt mà và nhanh nhẹn hơn</p><p>CÔNG DỤNG: </p><p>Giày bóng rổ chuyên đánh Outdoor, với thiết kế và công nghệ đế độc quyền chỉ có trên các dòng cao cấp nhà PEAK giúp bạn cày bền bỉ trên mọi loại sân chống trơn trượt chống mài mòn. Phần thiết kế thân giày và cổ giày bảo vệ chân, phản hồi chuyển động, bức tốc và hỗ trợ bật nhảy tốt. Có thể sử dụng chơi các bộ môn thể thao tương tự: cầu lông, bóng rổ indoor, chạy bộ đi bộ nhẹ nhàng</p>'
        },
        {
            id: 'peak-4',
            name: 'Giày PEAK Andrew Wiggins AW Talent-1 ET41057A – Xanh Lam',
            price: 2241000,
            image: './images/product/peak/product4.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p>Tên sản phẩm: Giày  bóng rổ nam PEAK BASKETBALL ET41057A<br>- Ưu điểm nổi bật: hấp thụ va đập, chống trượt, chống mài mòn, thoáng khí, hỗ trợ, cân bằng, chống va đập, nhẹ, phục hồi<br>- Chất liệu: vải lưới thoáng khí, nhẹ linh hoạt tạo nên tổng thể vừa vặn, thoải mái giúp đôi chân dễ thở sau mỗi trận bóng</p><p>- Đế giữa P –SOON với công nghệ kép Super P-Motive mang lại cho đế giữa hiệu suất phục hồi và đàn hồi giống như một tấm phản lực với độ bật nảy lên đến 65% giúp khởi động nhanh và gia tăng khả năng phản hồi năng lượng </p><p>- Công nghệ PEAK Taichi ở đệm đế sau hỗ trợ quá trình đàn hồi tiếp đất một cách êm ái  khi bật nhảy đồng thời giảm trọng lượng cho giày</p><p>- Cấu trúc khung TPU kết hợp công nghệ  P- ULTRALIGHT bao quanh ba chiều ở gót chân hỗ trợ khả năng tiếp đất mạnh mẽ, tăng khả năng truyền lực, phản hồi năng lượng cho từng chuyển động trên sân.</p><p>-Đế ngoài cao su vân đế rãnh sâu tăng độ bám sân tốt và chống trơn trượt, mài mòn </p><p>CÔNG DỤNG: </p><p>Giày bóng rổ chuyên đánh Outdoor, với thiết kế và công nghệ đế độc quyền chỉ có trên các dòng cao cấp nhà PEAK giúp bạn cày bền bỉ trên mọi loại sân chống trơn trượt chống mài mòn. Phần thiết kế thân giày và cổ giày bảo vệ chân, phản hồi chuyển động, bức tốc và hỗ trợ bật nhảy tốt.<br>Có thể sử dụng chơi các bộ môn thể thao tương tự: cầu lông, bóng rổ indoor, chạy bộ đi bộ nhẹ nhàng</p>'
        },
        {
            id: 'peak-5',
            name: 'Giày Bóng Rổ Nam PEAK Andrew Wiggins AW2 ET41017A – Trắng Xanh Lam',
            price: 2961000,
            image: './images/product/peak/product5.jpg',
            sizes: ['40', '41', '42', '43', '44'],
            description: '<p>Tên sản phẩm: Giày  bóng rổ nam PEAK TAICHI WIGGINS AW2 SIGNATURE ET41017A<br>- Ưu điểm nổi bật: hấp thụ va đập, chống trượt, chống mài mòn, thoáng khí, hỗ trợ, cân bằng, chống va đập, nhẹ, phục hồi<br>- Chất liệu: vải dệt bằng sợi nylon cường độ cao kết hợp lụa TPU vừa thoải mái vừa chắc chắn</p><p>- Đế giữa với cấu trúc cải tiến “hệ thống ba lõi” công nghệ mặt trên SURFACE PRO mới, cấu trúc P- ULTRALIGHT khung TPU bao quanh ba chiều ở gót chân hỗ trợ khả năng tiếp đất mạnh mẽ, tăng khả năng truyền lực, phản hồi năng lượng cho từng chuyển động trên sân</p><p>- Công nghệ PEAK Taichi phản hồi năng lượng đàn hồi tạo sự êm ái khi tiếp đất, giảm trọng lượng giày kết hợp với tấm cacbon hỗ trợ bật nhảy tăng tốc, hấp thụ sốc và bật lại nhanh chóng, giảm mức tiêu thụ năng lượng </p><p>-Đế ngoài cao su chống trơn trượt tăng độ bám, chống mài mòn </p><p>- Mạnh mẽ hơn trên sân với Wiggins thế hệ thứ 2 AW2 với thiết kế chuyên nghiệp khơi dậy niềm khao khát chiến đấu thực sự</p><p>CÔNG DỤNG:<br>Giày bóng rổ chuyên đánh Indoor, với thiết kế và công nghệ đế độc quyền chỉ có trên các dòng cao cấp nhà PEAK. Phần thiết kế thân giày và cổ giày bảo vệ chân, phản hồi chuyển động, bức tốc và hỗ trợ bật nhảy tốt. </p>'
        },
    ],
}
export {products};